version: '3'
services:
  web:
    build:
      context: .
      args:
        config_type: development
    command: flask run --host 0.0.0.0 --port 5000
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:10.3
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
